#!/bin/sh

for p in $(sudo /sbin/iptables-save |
           gawk 'match($0, "^-A PREROUTING .* -j REDIRECT --to-ports ([0-9]+)$", m) { print m[1] }')
do
	ss -Hntl "sport = :$p" | grep -q '' || { echo $p; exit; }
done

echo 0

## END ##
